export const XMPP_CONNECTION_AUTO_CONNECT = 'XMPP_CONNECTION_AUTO_CONNECT';
export const XMPP_CONNECTION_CONNECTING = 'XMPP_CONNECTION_CONNECTING';
export const XMPP_CONNECTION_CONNECTED = 'XMPP_CONNECTION_CONNECTED';
export const XMPP_CONNECTION_FAILED = 'XMPP_CONNECTION_FAILED';

export const ROOMS_SET = 'ROOMS_SET';
export const DISCOVER_SHOW = 'DISCOVER_SHOW';
export const DISCOVER_ITEMS = 'DISCOVER_ITEMS';
export const SUBDOMAINS_SET = 'SUBDOMAINS_SET';

export const USER_SET = 'USER_SET';
export const MY_STATUS_SET = 'MY_STATUS_SET';
export const MY_VCARD_SET = 'MY_VCARD_SET';
export const VCARD_SET = 'VCARD_SET';

export const PRESENCE_SET = 'PRESENCE_SET';

export const CHANNEL_ADD = 'CHANNEL_ADD';
export const CHANNEL_REMOVE = 'CHANNEL_REMOVE';
export const CHANNEL_SELECT = 'CHANNEL_SELECT';
export const CHANNEL_SET_SCROLL_POSITION = 'CHANNEL_SET_SCROLL_POSITION';
export const CHANNEL_SELECT_USER = 'CHANNEL_SELECT_USER';
export const CHANNELS_SET = 'CHANNELS_SET';

export const MESSAGE_SEND = 'MESSAGE_SEND';
export const MESSAGE_RECEIVE = 'MESSAGE_RECEIVE';

export const THEME_SET = 'THEME_SET';
export const THEME_SET_DEFAULT = 'THEME_SET_DEFAULT';

export const SETTINGS_TOGGLE = 'SETTINGS_TOGGLE';
export const LOG_OFF = 'LOG_OFF';

export const SNACKBAR_NOTIFICATION_ADD = 'SNACKBAR_NOTIFICATION_ADD';
export const SNACKBAR_NOTIFICATION_REMOVE = 'SNACKBAR_NOTIFICATION_REMOVE';

export const SETTINGS_NOTIFICATIONS_SET = 'SETTINGS_NOTIFICATIONS_SET';
export const SETTINGS_MESSAGES_SET = 'SETTINGS_MESSAGES_SET';
